-- ============================================
-- Clinical Flowsheet AI
-- Snowflake environment setup
-- ============================================

CREATE DATABASE IF NOT EXISTS CLINICAL_FLOWSHEET_AI;

CREATE SCHEMA IF NOT EXISTS CLINICAL_FLOWSHEET_AI.RAW;

CREATE SCHEMA IF NOT EXISTS CLINICAL_FLOWSHEET_AI.KNOWLEDGE;


CREATE OR REPLACE TABLE
CLINICAL_FLOWSHEET_AI.RAW.FLOWSHEET_MAPPING (

    NURSINGCHARTCELLTYPECAT       VARCHAR,
    NURSINGCHARTCELLTYPEVALLABEL VARCHAR,
    NURSINGCHARTCELLTYPEVALNAME  VARCHAR,
    RECORD_COUNT                 NUMBER,

    STANDARD_DOMAIN              VARCHAR,
    STANDARD_METRIC              VARCHAR,
    AI_REASON                    VARCHAR,

    MAPPING_STATUS               VARCHAR,
    MAPPING_SOURCE               VARCHAR
);