-- ============================================
-- Validate AI mappings against trusted knowledge
-- ============================================

UPDATE CLINICAL_FLOWSHEET_AI.RAW.FLOWSHEET_MAPPING M

SET M.MAPPING_STATUS = 'KNOWLEDGE_VALIDATED'

FROM CLINICAL_FLOWSHEET_AI.KNOWLEDGE.METRIC_KNOWLEDGE K

WHERE M.MAPPING_SOURCE = 'CORTEX_RAG'
  AND M.MAPPING_STATUS = 'PENDING_REVIEW'
  AND M.STANDARD_DOMAIN = K.STANDARD_DOMAIN
  AND M.STANDARD_METRIC = K.STANDARD_METRIC;


  SELECT
    NURSINGCHARTCELLTYPEVALNAME,
    STANDARD_DOMAIN,
    STANDARD_METRIC,
    MAPPING_SOURCE,
    MAPPING_STATUS

FROM CLINICAL_FLOWSHEET_AI.RAW.FLOWSHEET_MAPPING

WHERE MAPPING_SOURCE = 'CORTEX_RAG'

ORDER BY NURSINGCHARTCELLTYPEVALNAME;