-- ============================================
-- Human review / normalization of AI candidates
-- ============================================

UPDATE CLINICAL_FLOWSHEET_AI.KNOWLEDGE.METRIC_CANDIDATES
SET
    PROPOSED_DOMAIN = 'RESPIRATORY',
    PROPOSED_METRIC = 'RESPIRATORY_RATE',
    REVIEW_STATUS = 'APPROVED'
WHERE SOURCE_METRIC = 'Respiratory Rate';


UPDATE CLINICAL_FLOWSHEET_AI.KNOWLEDGE.METRIC_CANDIDATES
SET
    PROPOSED_DOMAIN = 'HEMODYNAMIC',
    PROPOSED_METRIC = 'NON_INVASIVE_SYSTOLIC_BLOOD_PRESSURE',
    REVIEW_STATUS = 'APPROVED'
WHERE SOURCE_METRIC = 'Non-Invasive BP Systolic';


UPDATE CLINICAL_FLOWSHEET_AI.KNOWLEDGE.METRIC_CANDIDATES
SET
    PROPOSED_DOMAIN = 'HEMODYNAMIC',
    PROPOSED_METRIC = 'NON_INVASIVE_DIASTOLIC_BLOOD_PRESSURE',
    REVIEW_STATUS = 'APPROVED'
WHERE SOURCE_METRIC = 'Non-Invasive BP Diastolic';


UPDATE CLINICAL_FLOWSHEET_AI.KNOWLEDGE.METRIC_CANDIDATES
SET
    PROPOSED_DOMAIN = 'HEMODYNAMIC',
    PROPOSED_METRIC = 'NON_INVASIVE_MEAN_ARTERIAL_PRESSURE',
    REVIEW_STATUS = 'APPROVED'
WHERE SOURCE_METRIC = 'Non-Invasive BP Mean';


UPDATE CLINICAL_FLOWSHEET_AI.KNOWLEDGE.METRIC_CANDIDATES
SET
    PROPOSED_DOMAIN = 'VITAL_SIGN',
    PROPOSED_METRIC = 'BODY_TEMPERATURE',
    REVIEW_STATUS = 'APPROVED'
WHERE SOURCE_METRIC IN ('Temperature (F)', 'Temperature (C)');


UPDATE CLINICAL_FLOWSHEET_AI.KNOWLEDGE.METRIC_CANDIDATES
SET
    PROPOSED_DOMAIN = 'VITAL_SIGN',
    PROPOSED_METRIC = 'TEMPERATURE_SITE',
    REVIEW_STATUS = 'APPROVED'
WHERE SOURCE_METRIC = 'Temperature Location';


UPDATE CLINICAL_FLOWSHEET_AI.KNOWLEDGE.METRIC_CANDIDATES
SET
    PROPOSED_DOMAIN = 'HEMODYNAMIC',
    PROPOSED_METRIC = 'INVASIVE_SYSTOLIC_BLOOD_PRESSURE',
    REVIEW_STATUS = 'APPROVED'
WHERE SOURCE_METRIC = 'Invasive BP Systolic';


UPDATE CLINICAL_FLOWSHEET_AI.KNOWLEDGE.METRIC_CANDIDATES
SET
    PROPOSED_DOMAIN = 'HEMODYNAMIC',
    PROPOSED_METRIC = 'INVASIVE_DIASTOLIC_BLOOD_PRESSURE',
    REVIEW_STATUS = 'APPROVED'
WHERE SOURCE_METRIC = 'Invasive BP Diastolic';


UPDATE CLINICAL_FLOWSHEET_AI.KNOWLEDGE.METRIC_CANDIDATES
SET
    PROPOSED_DOMAIN = 'HEMODYNAMIC',
    PROPOSED_METRIC = 'INVASIVE_MEAN_ARTERIAL_PRESSURE',
    REVIEW_STATUS = 'APPROVED'
WHERE SOURCE_METRIC = 'Invasive BP Mean';