-- ============================================
-- Promote HUMAN-APPROVED mappings
-- into trusted RAG knowledge
-- ============================================

MERGE INTO CLINICAL_FLOWSHEET_AI.KNOWLEDGE.METRIC_KNOWLEDGE K

USING (

    SELECT
        REVIEWED_DOMAIN AS STANDARD_DOMAIN,
        REVIEWED_METRIC AS STANDARD_METRIC,

        MIN(AI_REASON) AS DEFINITION,

        LISTAGG(DISTINCT SOURCE_METRIC, ', ')
        WITHIN GROUP (ORDER BY SOURCE_METRIC) AS KNOWN_ALIASES

    FROM CLINICAL_FLOWSHEET_AI.KNOWLEDGE.METRIC_CANDIDATES

    WHERE REVIEW_STATUS = 'APPROVED'
      AND REVIEWED_DOMAIN IS NOT NULL
      AND REVIEWED_METRIC IS NOT NULL

    GROUP BY
        REVIEWED_DOMAIN,
        REVIEWED_METRIC

) C

ON  K.STANDARD_DOMAIN = C.STANDARD_DOMAIN
AND K.STANDARD_METRIC = C.STANDARD_METRIC

WHEN NOT MATCHED THEN
INSERT (
    STANDARD_DOMAIN,
    STANDARD_METRIC,
    DEFINITION,
    KNOWN_ALIASES,
    SEARCH_TEXT
)
VALUES (
    C.STANDARD_DOMAIN,
    C.STANDARD_METRIC,
    C.DEFINITION,
    C.KNOWN_ALIASES,

    'Domain: ' || C.STANDARD_DOMAIN ||
    ' | Metric: ' || C.STANDARD_METRIC ||
    ' | Definition: ' || C.DEFINITION ||
    ' | Known aliases: ' || C.KNOWN_ALIASES
);